name: Deploy to GitHub Pages

on:
  # 当推送到main分支时触发
  push:
    branches: [ main ]
  # 允许从 Actions 选项卡手动触发工作流
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# 允许一个并发部署
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: 'npm'
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Install dependencies
        run: npm ci
      - name: Build with Astro
        run: npm run build
      - name: Inspect build output
        run: |
          echo "==== Build Output Structure ===="
          ls -la dist
          echo "==== Data Directory ===="
          ls -la dist/data || echo "No data directory found"
          echo "==== TZB Directory ===="
          ls -la dist/tzb || echo "No tzb directory found"
          echo "==== TZB/Data Directory ===="
          ls -la dist/tzb/data || echo "No tzb/data directory found"
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 